config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get 'pages/gallery'
  get 'pages/about_us'
  get 'pages/hunting_information'
  get 'pages/book_now'
  get 'pages/contact_us'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def gallery
    @image_paths = Dir.glob("#{Rails.root}/app/assets/images/*.JPG")
    @image_paths.concat Dir.glob("#{Rails.root}/app/assets/images/*.PNG")
    @image_paths.map!{ |path| path.split('/').last()}
    @col_1 = @image_paths.take(@image_paths.size / 3)
    @image_paths = @image_paths - @col_1
    @col_2 = @image_paths.take(@image_paths.size / 2)
    @image_paths = @image_paths - @col_2
    @col_3 = @image_paths
  end

  def about_us
  end

  def hunting_information
  end

  def book_now
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/info/_hunting_prices.html.erb
<p>The following prices will be in effect for the 2021 hunting seasons </p>
<h2>2021 Spring Turkey (Archery or Shotgun)</h2>
<p>2021 Spring Turkey Season Opening Week $650.00 <b>Per hunter</b> for 5 days/4 nights   $850.00 for 7 days/6 nights <b>Per hunter</b> </p>
<p>Remaining 2021 Spring Turkey Season $500.00 <b>Per hunter</b> for 5 days/4 nights.  $650.00 for 7 days/6 nights.  <b>Per hunter</b></p>

<h2>2021 Deer Season/Fall Turkey Season (ARCHERY ONLY)</h2>
<h3>NO SHOTGUNS IN FALL TURKEY SEASON</h3>
<p>(Opening Week) $1000.00 for 5 days/4 nights $1200.00 for 7 days/ 6 nights <b>Per hunter</b> </p>
<p>Rut Weeks $1000.00 for 5 days/4 nights or $1200.00 for 7 days/6 nights <b>Per hunter</b></p>
<p>Regular Bow $800.00 for 5 days/4 nights or $1000.00 for 7 days/6 nights <b>Per hunter</b></p>


  
<p>Lake Liberty is located within 6 miles of the Cabin, and Lake Cumberland is only a half hour away, we are located in the middle of Amish country, so don’t be surprised to see Horse and Buggies on the roads. </p> 
<p>Genesis Taxadermy </p>
<p>Johnny Baker: 606-669-8771 </p>
<p>Lancaster, KY  johnnydbaker@gmail.com </p>
<p>Genesistaxidermy.com</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LazyERanch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <h1> Serenity Cabin at Lazy E Ranch </h1>
    </div>
    <div id="navbar">
      <%= render 'partials/navigation_bar' %>
    </div>

    <div id = "content" >
      <%= yield %>
    </div>
    <div id="footer">
      <%= render 'partials/footer' %>
    </div>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class='top_image'>
  <%= image_tag "IMG_7442.jpg", size: "500x600"%>
</div>
<div class='body_text'>
  <h2>About Us</h2>
  <h3 id='udrl'>Meet Your Hosts</h3>

  <p>My name is Lee Etris, Sharon Etris is my better half, we have 3 children all boys, Dalton age 29 is Active Duty Air Force, Dylan age 21 a Senior at the University of Kentucky in the Computer Engineering Program, and Christian age 13 8th grade, helps out with the Ranch. I am retired from the US Department of Justice, and a Veteran of the US Navy, and the US Army. My wife Sharon is a Middle School Teacher, 6th grade, has 3 degrees, and was a successful Travel Agent for 15 years.
  <br><br>We love the outdoors, hunting, fishing, and Camping, and we hope that you and your family will enjoy our Serenity Cabin and Lazy E Hunting Ranch. </p>

</div>

app/views/pages/book_now.html.erb
<h2>Book Now</h2>

app/views/pages/contact_us.html.erb
<h2>Contact Us</h2>

app/views/pages/gallery.html.erb
<div class='body_text'>
  <h2>Gallery</h2>
</div>
<% if @image_paths %>
  <div class="gallery">
    <div class='row'>
      <div class='column'>
        <% @col_1.each { |image| %>
            <%= image_tag image %>
        <% } %>
      </div>
      <div class='column'>
        <% @col_2.each { |image| %>
            <%= image_tag image %>
        <% } %>
      </div>
      <div class='column'>
        <% @col_3.each { |image| %>
            <%= image_tag image %>
        <% } %>
      </div>
    </div>
  </div>
<% else %>
  <h3>No pictures to display</h3>
<% end %>

app/views/pages/home.html.erb
<div class='top_image' >
  <%= image_tag 'IMG_3446.JPG' %>
</div>
<div class='body_text'>
  <%= render 'info/home_info' %> 
</div>

app/views/pages/hunting_information.html.erb
<div class='top_image' >
  <%= image_tag 'IMG_1024.JPG' %>
</div>
<div class='body_text'>
  <h2>Hunting Information</h2>
  <%= render 'info/hunting_info' %> 
  <%= render 'info/hunting_prices' %>
</div>

app/views/partials/_footer.html.erb
<ul>
  <li><p>Phone number: 606-383-3939</p> </li>
  <li><p>Email: etris1965@gmail.com</p> </li>
  <li><%= link_to 'AirBnb', 'https://www.airbnb.com/h/serenerusticcabin' %></li>
</ul>

app/views/partials/_navigation_bar.html.erb
<ul>
  <li> <%= link_to 'Home', pages_home_path %> </li>
  <li> <%= link_to 'About Us', pages_about_us_path %> </li>
  <li> <%= link_to 'Gallery', pages_gallery_path %> </li>
  <li> <%= link_to 'Hunting Information', pages_hunting_information_path %> </li>
</ul>